import { Role } from "../enums/Role";
import { Education } from "./Education";
import { SocialMediaProfile } from "./SocialMediaProfile";
import { UserActivity } from "./UserActivity";
import { UserLesson } from "./UserLesson";
import { WorkExperience } from "./WorkExperience";
import { UserAnswer } from "./UserAnswer";
import { Ticket } from "./Ticket";
import { TicketAnswer } from "./TicketAnswer";
import { ExternalLoginType } from "../enums/ExternalLoginType";
import { FrontendTheme } from "./FrontendTheme";
import { Theme } from "./Theme";
import { UserSubscription } from "./UserSubscription";

export interface User {
  id?: string;
  fullName?: string;
  avatarUrl?: string;
  dateOfBirth?: string;
  emailAddress?: string;
  passwordHash?: string;
  city?: string;
  role: Role;
  educations: Education[];
  workExperiences: WorkExperience[];
  resumeText?: string;
  aboutMe?: string;
  socialMediaProfiles: SocialMediaProfile[];
  userActivities: UserActivity[];
  userAnswers: UserAnswer[];
  userLessons: UserLesson[];
  tickets: Ticket[];
  ticketAnswers: TicketAnswer[];
  username: string;
  externalLoginId?: string;
  externalLoginType?: ExternalLoginType;
  themeId: string;
  theme?: Theme;
  userSubscriptions: UserSubscription[];
}
